name: FTP Deploy on Release

on:
  release:
    types: [published] # Sadece bir release yayınlandığında çalışır

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 🔧 Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: 📂 Upload files to FTP and disconnect
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: |
          lftp -c "
          open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_SERVER
          mirror -R --verbose ./site/ ./domains/capsule.net.tr/public_html/
          bye
          "
